name: Gradle
on:
  push:
    branches:
      - main
      - beta
jobs:
  build:
    strategy:
      matrix:
        java-version: [ 21 ]
        runs-on: [ubuntu-latest]
    name: Build on ${{ matrix.runs-on }} with jdk ${{ matrix.java-version }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js and semantic-release plugins
        uses: actions/setup-node@v4
      - run: npm install -g semantic-release@21.0.5 @semantic-release/github@8.1.0 @semantic-release/changelog@6.0.2 @semantic-release/commit-analyzer@10.0.2 @semantic-release/exec@6.0.3 @semantic-release/git@10.0.1 @semantic-release/release-notes-generator@11.0.4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
